import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import tailwindcss from '@tailwindcss/vite'
import { resolve } from 'path'

// OmniDoc OS — Vite configuration tuned for client-side WASM, Web Workers,
// top-level await, and aggressive chunk splitting of heavy engines.
// NOTE: sitemap.xml + robots.txt are generated by scripts/generate-sitemap.mjs
// (run as a prebuild step) into public/, which Vite copies verbatim to dist/.
export default defineConfig({
  plugins: [vue(), tailwindcss()],
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src'),
    },
  },
  // ES-module workers so Comlink + dynamic imports work inside workers
  worker: {
    format: 'es',
  },
  optimizeDeps: {
    // pdfjs-dist and tesseract.js ship their own workers/wasm; let them resolve
    // at runtime instead of being pre-bundled (avoids broken worker URLs).
    exclude: ['pdfjs-dist', 'tesseract.js'],
  },
  build: {
    // ES2022 is a stable, widely-supported floor (Chrome 94+, FF 93+, Safari 15+)
    // that still supports top-level await used by the worker engines.
    target: 'es2022',
    chunkSizeWarningLimit: 2000,
  },
  // Cross-origin isolation for tesseract.js / WASM threading during dev.
  server: {
    headers: {
      'Cross-Origin-Opener-Policy': 'same-origin',
      'Cross-Origin-Embedder-Policy': 'credentialless',
    },
  },
})
